### PR TITLE
traslate install file

### PR DESCRIPTION
**Pull request by DarkFrank**
Translate file install.rst, please review, thanks.

### CODE REVIEW

**Comment by steve-chavez** [comment]
Hi @Lellansin. Are you still maintaining this repo?

**Review by Lellansin — APPROVED** [review]

**Comment by Lellansin** [comment]
Hi @steve-chavez , I'm still here. I'v sent collaborator Invite, in case that I'm too busy to visit Github.

**Comment by steve-chavez** [comment]
@Lellansin Thank you! Could you also add me as a maintainer on https://readthedocs.org/projects/postgrest-docs-chinese/?

**Comment by Lellansin** [comment]
@steve-chavez Sure, I have added you and begriffs as the maintainers of its.

**Pull request merged**
